import type { RecipeIngredient } from "./calculator";

const ingredients: RecipeIngredient[] = [
  {
    id: "pork",
    name: "Carne de cerdo (magro)",
    measurementType: "mass",
    mode: "percent",
    percentOfMeat: 80,
    displayUnit: "g",
    sortOrder: 0,
  },
  {
    id: "fat",
    name: "Tocino / panceta",
    measurementType: "mass",
    mode: "percent",
    percentOfMeat: 20,
    displayUnit: "g",
    sortOrder: 1,
  },
  {
    id: "salt",
    name: "Sal fina",
    measurementType: "mass",
    mode: "percent",
    percentOfMeat: 2.5,
    displayUnit: "g",
    sortOrder: 2,
  },
  {
    id: "cure",
    name: "Sal de cura #1",
    measurementType: "mass",
    mode: "percent",
    percentOfMeat: 0.25,
    displayUnit: "g",
    sortOrder: 3,
  },
  {
    id: "paprika-sweet",
    name: "Pimentón dulce",
    measurementType: "mass",
    mode: "percent",
    percentOfMeat: 1.5,
    displayUnit: "g",
    sortOrder: 4,
  },
  {
    id: "paprika-hot",
    name: "Pimentón picante",
    measurementType: "mass",
    mode: "percent",
    percentOfMeat: 0.5,
    displayUnit: "g",
    sortOrder: 5,
  },
  {
    id: "pepper",
    name: "Pimienta negra",
    measurementType: "mass",
    mode: "percent",
    percentOfMeat: 0.3,
    displayUnit: "g",
    sortOrder: 6,
  },
  {
    id: "wine",
    name: "Vino blanco",
    measurementType: "volume",
    defaultDensityGPerMl: 0.99,
    mode: "percent",
    percentOfMeat: 5,
    displayUnit: "ml",
    sortOrder: 7,
  },
  {
    id: "garlic",
    name: "Diente de ajo",
    measurementType: "count",
    mode: "absolute",
    amountCanonical: 4,
    displayUnit: "piece",
    sortOrder: 8,
  },
  {
    id: "casing",
    name: "Tripa natural",
    measurementType: "length",
    mode: "absolute",
    amountCanonical: 250,
    displayUnit: "cm",
    sortOrder: 9,
  },
];

export const demoRecipe = {
  title: "Chorizo criollo (demo)",
  versionNumber: 1,
  meatBaseGrams: 1000,
  meatBaseDisplayUnit: "kg" as const,
  ingredients,
};
