"use server";

import { createClient } from "@/lib/supabase/server";

export type AIIngredient = {
  name: string;
  mode: "percent" | "absolute";
  percent_of_meat?: number;
  amount_canonical?: number;
  canonical_unit: string;
  display_unit: string;
  density: number | null;
};

export type AIRecipe = {
  title: string;
  description: string;
  meat_base_grams: number;
  tags: string[];
  ingredients: AIIngredient[];
  steps: string[];
  explanation?: string;
};

function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80);
}

function inferMeasurementType(unit: string): "mass" | "volume" | "length" | "count" {
  if (["g", "kg", "oz", "lb"].includes(unit)) return "mass";
  if (["ml", "l", "floz", "tsp", "tbsp", "cup"].includes(unit)) return "volume";
  if (["cm", "m"].includes(unit)) return "length";
  return "count";
}

function inferCategory(name: string): string {
  const lower = name.toLowerCase();
  if (["cerdo", "ternera", "pollo", "paleta", "tocino", "panceta", "magro", "pork", "beef", "chicken"].some((k) => lower.includes(k))) return "meat";
  if (["sal", "cura", "nitrito", "nitrato", "dextrosa", "salt", "cure"].some((k) => lower.includes(k))) return "cure";
  if (["pimentón", "pimienta", "ajo", "comino", "orégano", "chile", "paprika", "pepper", "garlic", "cumin"].some((k) => lower.includes(k))) return "spice";
  if (["vino", "vinagre", "agua", "leche", "crema", "wine", "vinegar", "water", "milk"].some((k) => lower.includes(k))) return "liquid";
  if (["tripa", "hilo", "colágeno", "casing", "string"].some((k) => lower.includes(k))) return "casing";
  return "other";
}

export async function saveAIRecipe(aiRecipe: AIRecipe): Promise<{ recipeId: string }> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) throw new Error("Not authenticated");

  const { data: dbIngredients = [] } = await supabase
    .from("ingredients")
    .select("id, name, measurement_type, default_density_g_per_ml, category");

  const resolvedIds: { id: string; idx: number }[] = [];

  for (let i = 0; i < aiRecipe.ingredients.length; i++) {
    const aiIng = aiRecipe.ingredients[i];
    const normalized = aiIng.name.toLowerCase().trim();

    const match = (dbIngredients ?? []).find(
      (db) => db.name.toLowerCase().trim() === normalized,
    );

    if (match) {
      resolvedIds.push({ id: match.id, idx: i });
    } else {
      const measurementType = inferMeasurementType(aiIng.canonical_unit);
      const category = inferCategory(aiIng.name);
      const { data: newIng, error } = await supabase
        .from("ingredients")
        .insert({
          name: aiIng.name,
          measurement_type: measurementType,
          default_density_g_per_ml: aiIng.density,
          category,
          created_by: user.id,
        })
        .select("id")
        .single();

      if (error || !newIng) throw new Error("Failed to create ingredient: " + error?.message);
      resolvedIds.push({ id: newIng.id, idx: i });
    }
  }

  const slug = slugify(aiRecipe.title) || "recipe";
  const { data: recipe, error: recErr } = await supabase
    .from("recipes")
    .insert({
      owner_id: user.id,
      slug,
      title: aiRecipe.title,
      description: aiRecipe.description,
      visibility: "private",
    })
    .select("id")
    .single();

  if (recErr || !recipe) throw new Error("Failed to create recipe: " + recErr?.message);

  const instructions = aiRecipe.steps.map((s, i) => `${i + 1}. ${s}`).join("\n");
  const { data: version, error: verErr } = await supabase
    .from("recipe_versions")
    .insert({
      recipe_id: recipe.id,
      version_number: 1,
      change_note: "Generated by Don Marco AI",
      instructions,
      meat_base_weight_grams: aiRecipe.meat_base_grams,
      meat_base_display_unit: "g",
      created_by: user.id,
    })
    .select("id")
    .single();

  if (verErr || !version) throw new Error("Failed to create version: " + verErr?.message);

  const versionIngredients = resolvedIds.map(({ id, idx }) => {
    const aiIng = aiRecipe.ingredients[idx];
    const displayUnit = aiIng.display_unit || aiIng.canonical_unit;

    if (aiIng.mode === "percent") {
      return {
        version_id: version.id,
        ingredient_id: id,
        mode: "percent" as const,
        percent_of_meat: (aiIng.percent_of_meat ?? 0) / 100,
        amount_canonical: null,
        display_unit: displayUnit,
        sort_order: idx,
      };
    }
    return {
      version_id: version.id,
      ingredient_id: id,
      mode: "absolute" as const,
      percent_of_meat: null,
      amount_canonical: aiIng.amount_canonical ?? 0,
      display_unit: displayUnit,
      sort_order: idx,
    };
  });

  const { error: ingErr } = await supabase
    .from("recipe_version_ingredients")
    .insert(versionIngredients);

  if (ingErr) throw new Error("Failed to save ingredients: " + ingErr.message);

  return { recipeId: recipe.id };
}
